import Head from "next/head";
import Layout from "@/components/layout";
import { Box, Button, Stack } from "@mui/material";
import Section from "@/components/section";
import CalendarMonthIcon from "@mui/icons-material/CalendarMonth";
import FunctionsIcon from "@mui/icons-material/Functions";
import PublicIcon from "@mui/icons-material/Public";
import CloudDownloadIcon from "@mui/icons-material/CloudDownload";
import { CloudUpload } from "@mui/icons-material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box>
          <Section
            title="Calendario"
            icon={<CalendarMonthIcon fontSize="large" />}
          >
            <Stack direction={"row"} gap={2}>
              <Button variant="contained" startIcon={<CloudDownloadIcon />}>
                Descargar template
              </Button>
              <Button variant="contained" startIcon={<CloudUpload />}>
                Subir archivo
              </Button>
              <Box>
                <Button variant="contained" startIcon={<CloudDownloadIcon />}>
                  Descargar reciente
                </Button>
              </Box>
            </Stack>
          </Section>
          <Section
            title="Variables fijas"
            icon={<PublicIcon fontSize="large" />}
          >
            <Box>Calendario</Box>
          </Section>
          <Section
            title="Variables extras"
            icon={<FunctionsIcon fontSize="large" />}
          >
            <Stack direction={"row"} gap={2}>
              <Button variant="contained" startIcon={<CloudDownloadIcon />}>
                Descargar template
              </Button>
              <Button variant="contained" startIcon={<CloudUpload />}>
                Subir archivo
              </Button>
              <Box>
                <Button variant="contained" startIcon={<CloudDownloadIcon />}>
                  Descargar reciente
                </Button>
              </Box>
            </Stack>
          </Section>
        </Box>
      </Layout>
    </>
  );
}
